CSS/Desktop/header.css, HTML/index.html
close #5 skapat en header! OBS lade till metadata i index.html
=> 5 create header

.vscode/settings.json, CSS/Desktop/header.css, CSS/Desktop/sidebar.css, HTML/index.html
=> added sidebar and its containers

CSS/Desktop/sidebar.css, HTML/index.html, JS/today.js
=> welcome segment completed

CSS/Desktop/main.css, JS/calender.js
=> generates day-divs based on amount of days current month

CSS/Desktop/header.css, CSS/Desktop/sidebar.css, HTML/index.html, JS/today.js
=> added add todo item button, inc script and css

CSS/Desktop/header.css, CSS/Desktop/sidebar.css, CSS/global.css, HTML/index.html
=> 14 create global css file

CSS/Desktop/sidebar.css, HTML/index.html
=> refactored main layout

CSS/Desktop/sidebar.css, HTML/index.html, JS/todo.js
=> 20 html forms to js object

HTML/index.html, JS/calender.js
=> added buttons to change month

CSS/Desktop/main.css, JS/calender.js
=> refactored renderCalendar!

JS/todo.js
=> fixed bug with empty local storage

JS/calender.js
=> amount of todos now shows on day

.vscode/settings.json, CSS/global.css, JS/calender.js, JS/todo.js
=> 24 create function for deleting todos!

CSS/Desktop/main.css, JS/calender.js
close #30
fixed basic. need to style and maybe refactor calendar or move some functions its gettinng meesssy
=> printing holidays

CSS/Desktop/main.css, CSS/global.css, HTML/index.html, JS/calender.js
close #19 
more to be done. but we are happy for now
=> 19 redesign calendar

CSS/Desktop/sidebar.css, JS/calender.js, JS/todo.js
close #55  (also changed the design of todolist when no date is selected)
=> style todolist when date is selected

CSS/Desktop/main.css, CSS/Desktop/sidebar.css, JS/todo.js
close #55 fixed bug when title was too long in the todolist
=> title can no longer be to long

CSS/Desktop/main.css, JS/calender.js
fixes #53 still needs some work
=> 53 fix hover on days

CSS/Desktop/sidebar.css, HTML/index.html, JS/calender.js, JS/todo.js
close #28
its working to edit localstorage, but introduced some bugs, add todo item forms and some other stuff
=> 28 function to edit todo

CSS/Desktop/main.css, CSS/Desktop/sidebar.css
=> minor bug fixes

JS/todo.js
=> added validation to forms

JS/calender.js, JS/todo.js
=> fixed so edit form closes properly and clears when saved etc.

JS/calender.js
=> fixed selected day bug

CSS/Desktop/main.css, CSS/global.css, JS/calender.js
#58 Hover almost done 
Known issues:
faded background when over
fix:
background: none on .day when hover
Todo:
fix transition
=> More work on hover

CSS/Desktop/sidebar.css, HTML/index.html, JS/calender.js, JS/today.js, JS/todo.js
close #44
calling location api to get city, calling wheaterapi and access wheater with current city. design needs work
=> 44 fetch weather info

JS/today.js
=> changed api for geolocation

CSS/Desktop/main.css, JS/calender.js
fixes #78 
selected day now a different color instead of border
=> fix selecting day issue

JS/todo.js
=> sorting-todos-by-date

JS/today.js
close #84
removed weekday array, and replaced currentday innerhtml with day from new date().localestring
=> redid logic for display current day

JS/today.js
close #87
close #86
fixed spelling too
=> handle different responses from location api

CSS/Desktop/header.css, CSS/Desktop/main.css, CSS/Desktop/sidebar.css, CSS/tablet.css, HTML/index.html, JS/header.js
part one of making site responsive, this pr is only for the rest of the group to be able to work alongside.
=> 90 make site responsive

CSS/Desktop/header.css, CSS/mobile.css, CSS/tablet.css
closes #90 weehoo 🎆🎈
also fixes #64
=> finished responsivity

CSS/Desktop/header.css, HTML/index.html
removed the scewed divs and applied gradient to container background
=> fixed bug with scew div in header

CSS/Desktop/main.css
=> fixed bug with overflow on flagdays and todo

CSS/Desktop/sidebar.css
removed height on modal and added padding on save and close btn
=> fixed some design issues with editmodal

CSS/Desktop/main.css, CSS/tablet.css
=> fixed flag overflow into next day

CSS/Desktop/sidebar.css, CSS/tablet.css, HTML/index.html, JS/today.js, JS/variables.js
closes #97 . added icon from fontawesome and now also displaying city
=> 97 redesign weather section

CSS/Desktop/sidebar.css, CSS/mobile.css, CSS/tablet.css, HTML/index.html
closes #115
more work, but need to merge so you can work on it boooooiis 🤷‍♀️
=> fixed some alignments and buttonsizes etc.

JS/todo.js
=> bug fixed when editing todo in the past

CSS/Desktop/sidebar.css, JS/todo.js
=> added-checkbTn-for-showDayInfo

CSS/Desktop/sidebar.css, CSS/mobile.css, CSS/tablet.css
=> fixed scroll and overfloww issues

JS/calendar.js, index.html
=> fixed github pages
